[package]
name = "ManualRule"
version = "0.0.1"
edition = "2024"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet" }
XOracle = {local = "../x_oracle"}

[addresses]
manual_rule = "0x0"
