[package]
name = "ProtocolQuery"
version = "0.0.1"

[dependencies]
# Use single-line format so deploy-all can update rev automatically
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet" }
Creek = { local = "../../contracts/protocol" }

[addresses]
protocol_query = "0x0"


